media/media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include("news.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("django.contrib.auth.urls")),
    path('api-auth/', include('rest_framework.urls')),
    
]

media/news/urls.py
from django.urls import path
from . import views

app_name = "news"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:news_id>/", views.detail, name="detail"),
    path("add/", views.add, name="add"),
    path("<int:news_id>/edit/", views.NewsEditView.as_view(), name="edit_news"),
    path("sign-up/", views.sign_up, name="sign_up"),
    path("<int:news_id>/delete-news/", views.delete_news, name="delete_news"),
    path("<int:news_id>/delete-comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),

    path("api/", views.api_index, name="api_index"),
    path("api/news", views.api_post, name="api_post"),
    # path("api/news/<int:pk>/", views.api_news_detail, name="api_news_detail"),
    path("api/news/<int:pk>/", views.NewsDetailView.as_view(), name="api_news_detail"),
    path("api/news/", views.NewsList.as_view(), name="api_news_list"),
]

media/news/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=250)
    created_at = models.TimeField(auto_now=True)

    def has_comments(self):
        return Comment.objects.filter(news=self).exists()

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    content = models.CharField(max_length=500)
    created_at = models.TimeField(auto_now=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE)

media/news/forms.py
from django import forms
from .models import News, Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ["title", "content"]

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
        ]

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

media/news/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import News, Comment
from django.views import View
from .forms import NewsForm, SignUpForm, CommentsForm
from django.contrib.auth.models import Group
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import generics, mixins, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import NewsSerializer

# Create your views here.
def index(request):
    news = News.objects.order_by("created_at").all()
    context = {"news": news}
    return render(request, "news/index.html", context)

def detail(request, news_id):
    try :
        news = News.objects.get(pk=news_id)
    except News.DoesNotExist:
        raise Http404("Not Found")
    
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.news = news
            comment.save()
            return HttpResponseRedirect(reverse("news:index"))
    else:
        CommentsForm()
        # content = request.POST['content']
        # Comment.objects.create(content=content, news=news)
        # latest_comment = Comment.objects.latest('created_at')
        # return redirect(reverse('news:detail', args=[news_id]))
    context = {"news": news}
    return render(request, "news/detail.html",context)


@login_required(login_url="/login/")
@permission_required("news.add_news", login_url="/login/")
def add(request):
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            news.author = request.user
            news.save()
            return HttpResponseRedirect(reverse("news:index"))
    else:
        form = NewsForm()
    return render(request, 'news/add.html')

class NewsEditView(View):
    def get(self, request, news_id):
        try :
            news = News.objects.get(pk=news_id)
        except News.DoesNotExist:
            raise Http404("Not Found")
        form = NewsForm(instance=news)
        return render(request, "news/news_edit.html", {"form": form, "news_id": news_id})
    
    def post(self, request, news_id):
        try :
            news = News.objects.get(pk=news_id)
        except News.DoesNotExist:
            raise Http404("Not Found")
        
        form = NewsForm(request.POST, instance=news)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("news:detail", args=(news_id,)))
        
def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            group = Group.objects.get(name="default")
            group.user_set.add(user)

            login(request, user)
            return redirect(reverse("news:index"))
    else:
        form = SignUpForm()

    return render(request, "registration/sign_up.html", {"form": form})

def delete_news(request, news_id):
    try :
        news = News.objects.get(pk=news_id)
    except News.DoesNotExist:
        raise Http404("Not Found")
    if request.method == "POST":
        if request.user == news.author or request.user.has_perm(
            "news.delete_news"
        ):
            news.delete()
    return redirect(reverse("news:index"))

def delete_comment(request, news_id, comment_id):
    try :
        news = News.objects.get(pk=news_id)
    except News.DoesNotExist:
        raise Http404("Not Found")
    
    try :
        comment = Comment.objects.get(pk=comment_id, news=news)
    except Comment.DoesNotExist:
        raise Http404("Not Found")
    
    if request.method == "POST":
        if request.user == comment.author or request.user.has_perm(
            "news.delete_comment"
        ):
            comment.delete()
    return redirect(reverse("news:index"))

#api
def api_index(request):
    print(request.user.username)
    news = News.objects.all()
    serializer = NewsSerializer(news, many=True)

    return Response(serializer.data, status=418)

@api_view(["POST"])
def api_post(request):
    serializer = NewsSerializer(data=request.data)
    if serializer.is_valid():
        news = serializer.save()
        return Response({"detail": "save success", "news_id": news.id})
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class NewsDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer

class NewsList(generics.ListCreateAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer

media/news/templates/news/add.html
<body>
    <form action="{% url 'news:add'%}" method="post">
        {% csrf_token %}

        <h3>Add news:</h3>
        <p>Title</p>
        <input type="text" id="title" name="title"><br>
        <p>Content:</p>
        <textarea id="content" name="content"></textarea><br>
        <button type="submit">Submit</button>
    </form>
</body>

media/news/templates/news/base.html
<html>
    <head>
        {% load static  %}

        <title>media | {% block title %} {% endblock %}</title>
    </head>

    <body>
        {% block content %} {% endblock %}
    </body>
</html>

media/news/templates/news/detail.html
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>

<body>
    <h1>{{news.title}}</h1>
    <h2>{{news.content}}</h2>
    <h2>{{news.created_at}}</h2>

    {% if user.is_authenticated %}
        <a class="btn btn-outline-danger" href="{% url 'logout' %}">Выйти</a>
        <form  method="post">
            {% csrf_token %}

            <h3>Add comment:</h3>
            <p>Content:</p>
            <textarea id="content" name="content"></textarea><br>
            <button type="submit">Submit</button>
        </form>
        <p>Comments:</p>
        <ol>
            {% for comment in news.comment_set.all %}
                <li>
                    {{comment.content}} - {{comment.created_at}}
                </li>
                {% if user == comment.author or perms.news.delete_comment %}
                        <form action="{% url 'news:delete_comment' news.id comment.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" >Удалить</button>
                        </form>
                {% endif %}
            {% endfor %}
        </ol>
    {% else %}
        <p>Comments:</p>
        <ol>
            {% for comment in news.comment_set.all %}
                <li>
                    {{comment.content}} - {{comment.created_at}}
                </li>
            {% endfor %}
        </ol>
    <li class="nav-item">
        <a class="btn btn-outline-danger" href="{% url 'logout' %}">Войти</a>
    </li>
        <h5>Add comment:</h5>
        <p>Доступно для авторизованных</p>
    {% endif %}
</body>

media/news/templates/news/index.html
<body>
    <ol>
        {% for new in news %}

            <li>
                <a href="{% url 'news:detail' new.id %}">{{new.title}}</a>
            </li>
            {% if user == new.author or perms.polls.delete_news %}
                <form action="{% url 'news:delete_news' new.id %}" method="post">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-danger" >Удалить</button>
                </form>
            {% endif %}
        {% endfor %}
        
    </ol>

</body>

media/news/templates/news/news_edit.html
{% extends "news/base.html" %}

{% block title %} Edit {% endblock %}

{% block content %}

    <form action="{% url 'news:edit_news' news_id %}" method="post">
        {% csrf_token %}

        {{form}}

        <input type="submit">
    </form>

{% endblock %}